# Generated by Django 5.0.3 on 2024-03-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('State', models.CharField(choices=[('li', 'liquid'), ('so', 'solid')], max_length=2)),
                ('Quantity', models.FloatField(default=0)),
                ('Unit', models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('lbs', 'pound'), ('gr', 'gram'), ('kg', 'kilogram'), ('oz', 'ounce'), ('ml', 'mililitre'), ('li', 'litre'), ('glass', 'glass'), ('gal', 'gallon')], max_length=6)),
                ('Unit_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('Quantity', models.IntegerField(default=1)),
                ('Total_price', models.FloatField()),
                ('Menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.menuitem', verbose_name='Menu Item')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(default=0)),
                ('Unit', models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('lbs', 'pound'), ('gr', 'gram'), ('kg', 'kilogram'), ('oz', 'ounce'), ('ml', 'mililitre'), ('li', 'litre'), ('glass', 'glass'), ('gal', 'gallon')], max_length=6)),
                ('Ingradint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingradient', verbose_name='Recipe')),
                ('Menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem', verbose_name='Menu Item')),
            ],
        ),
    ]
