# Generated by Django 5.0.2 on 2024-03-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_reciperequirement_ingradint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.menuitem', verbose_name='Menu Item'),
        ),
    ]
