# Generated by Django 5.0.2 on 2024-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_profit_purcahsehistory_alter_purchase_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='Reating',
            field=models.IntegerField(default=3),
        ),
    ]
