# Generated by Django 5.0.3 on 2024-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_menuitem_reating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='Unit',
            field=models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('lbs', 'pound'), ('gr', 'gram'), ('kg', 'kilogram'), ('oz', 'ounce'), ('ml', 'mililitre'), ('li', 'litre'), ('glass', 'glass'), ('gal', 'gallon'), ('count', 'count')], default='gram', max_length=6),
        ),
    ]
