# Generated by Django 5.0.2 on 2024-04-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_reciperequirement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='Timestamp_end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profit',
            name='Timestamp_start',
            field=models.CharField(max_length=255),
        ),
    ]
